name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*'  # 仅在以 v 开头的标签推送时触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: dylanweb3/ckb-dev-all-in-one:${{ github.ref_name }}  # 使用 Git 标签作为版本


# name: Build and Push Docker Image
# 
# on:
#   push:
#     branches:
#       - main  # 触发条件，可以根据需要修改为其他分支
# 
# jobs:
#   build:
#     runs-on: ubuntu-latest
# 
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
# 
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v1
# 
#       - name: Login to Docker Hub
#         uses: docker/login-action@v1
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}
# 
#       - name: Build and push
#         uses: docker/build-push-action@v2
#         with:
#           context: .
#           push: true
#           tags: dylanweb3/ckb-dev-all-in-one:latest  # 替换为你的 Docker Hub 用户名和仓库名



